name: Draft release for Signum Node

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release Draft
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Wallets
        shell: bash
        run: |
          cd ./ci
          ./updatePhoenix.sh
          ./updateClassic.sh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Java 21 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build all artifacts
        run: ./gradlew shadowJar jpackageWin zipWinExe sourcesJar javadocJar release

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release Draft
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Signum Node ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload - signum-node.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node.zip
          asset_name: signum-node-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload - signum-node-win_x64.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node-win_x64.zip
          asset_name: signum-node-${{ env.VERSION }}-win_x64.zip
          asset_content_type: application/zip

      - name: Upload - Sources JAR
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/signum-node-sources.jar
          asset_name: signum-node-${{ env.VERSION }}-sources.jar
          asset_content_type: application/java-archive

      - name: Upload - Javadoc JAR
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/signum-node-javadoc.jar
          asset_name: signum-node-${{ env.VERSION }}-javadoc.jar
          asset_content_type: application/java-archive
