name: Draft release for Signum Node

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Wallets
        run: |
          cd ./ci
          ./updatePhoenix.sh
          ./updateClassic.sh

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build All
        run: ./gradlew release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Signum Node ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Upload Release Asset - Zip
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node.zip
          asset_name: signum-node-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Zip checksum
        id: upload-release-asset-zip-checksum
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/checksums/signum-node.zip.sha256
          asset_name: signum-node-${{ env.VERSION }}.zip.sha256
          asset_content_type: text/plain

      - name: Upload Release Asset - WindowsZip
        id: upload-release-asset-windows-zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node-win_x64.zip
          asset_name: signum-node-${{ env.VERSION }}-win_x64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - WindowsZip checksum
        id: upload-release-asset-windows-zip-checksum
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/checksums/signum-node-win_x64.zip.sha256
          asset_name: signum-node-${{ env.VERSION }}-win_x64.zip.sha256
          asset_content_type: text/plain

